### Pandas
[Pandas](https://pandas.pydata.org/) er et bibliotek for å manipulere og analysere tabeller. Det bruker egne objekter (datastrukturer), *Series* for endimensjonale tabeller og *DataFrame* for todimensjonale tabeller. *DataFrame* minner mye om et regneark eller en SQL-tabell med rader og kolonner. 

#### Lese inn DataFrame fra fil
Ofte vil vi lese inn dataene fra en fil med *pd.read_json()* eller *pd.read_csv()*, og *pandas* legger dataene inn i en *DataFrame*, gjerne med kolonneoverskrifter.

#### Lage en DataFrame fra lister av lister
Vi kan også opprette en *DataFrame* fra en liste med lister. Til å begynne med er radene og kolonnene angitt med indeksnummer, men vi kan gi dem navn med *df.index* og *df.columns*

In [2]:
import pandas as pd

lst = [[ 1, 2, 3, 4],
       [ 5, 6, 7, 8],
       [ 9,10,11,12],
       [13,14,15,16]]
df = pd.DataFrame(lst)
df

ModuleNotFoundError: No module named 'pandas'

In [ ]:
df.columns =['A','B','C','D']
df.index = ['Øst','Sør','Vest','Nord']
df

       A   B   C   D
Øst    1   2   3   4
Sør    5   6   7   8
Vest   9  10  11  12
Nord  13  14  15  16

Vi kan bruke info() til å få ut informasjon om kolonnene.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, Øst to Nord
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
 3   D       4 non-null      int64
dtypes: int64(4)
memory usage: 160.0+ bytes

Vi kan plukke ut verdier til enkelt kolonner ved å angi kolonnenavnene i en liste inne i en indeksoperator `[['A', 'C']]` og vi kan gi betingelser til hvilke rader vi vil ha med

In [ ]:
BD = df[['B','D']]
type(BD)

       B   D
Øst    2   4
Sør    6   8
Vest  10  12
Nord  14  16

In [ ]:
type(df['B'])

pandas.core.series.Series

In [ ]:
df[df['A']>5]

       A   B   C   D
Vest   9  10  11  12
Nord  13  14  15  16

In [ ]:
df[df['A']>5][['B','D']]

       B   D
Vest  10  12
Nord  14  16

Vi kan også plukke ut rader og kolonner med *df.iloc* (indeksnummer) og *df.loc* (navn)

In [ ]:
df

       A   B   C   D
Øst    1   2   3   4
Sør    5   6   7   8
Vest   9  10  11  12
Nord  13  14  15  16

In [ ]:
df['B']

Øst      2
Sør      6
Vest    10
Nord    14
Name: B, dtype: int64

In [ ]:
df.iloc[([0,2],[1,3])]

       B   D
Øst    2   4
Vest  10  12

In [ ]:
df.loc[(['Øst','Vest'],['B','D'])]

       B   D
Øst    2   4
Vest  10  12

Vi kan legge til en ny kolonne med utregninger med normal tilordning *(SQL AS)* og fjerne den med *df.drop() (SQL DROP COLUMN)*.

In [ ]:
df['E']=df['A']*2
df

       A   B   C   D   E
Øst    1   2   3   4   2
Sør    5   6   7   8  10
Vest   9  10  11  12  18
Nord  13  14  15  16  26

In [ ]:
df = df.drop(columns='E')
df

       A   B   C   D
Øst    1   2   3   4
Sør    5   6   7   8
Vest   9  10  11  12
Nord  13  14  15  16

Skal vi legge til rader, lager vi først en *DataFrame* (rad) og så bruker vi *pd.concat()* til å legge til den, og skal vi fjerne dem kan vi bruke *df.drop()*

In [ ]:
nyrad = pd.DataFrame([[22,24,26,28]], \
    columns=['A','B','C','D'], \
    index=['Nord-Vest'])
df = pd.concat([df,nyrad])
df

            A   B   C   D
Øst         1   2   3   4
Sør         5   6   7   8
Vest        9  10  11  12
Nord       13  14  15  16
Nord-Vest  22  24  26  28

In [ ]:
df = df.drop(index='Nord-Vest')
df

       A   B   C   D
Øst    1   2   3   4
Sør    5   6   7   8
Vest   9  10  11  12
Nord  13  14  15  16

For å vise *sortering* og *gruppering* leser vi først inn et datasett fra fil. **homes.csv**, *Home sale statistics. Fifty home sales, with selling price, asking price, living space, rooms, bedrooms, bathrooms, age, acreage, taxes. There is also an initial header line.*

In [ ]:
url = 'https://people.sc.fsu.edu/~jburkardt/data/csv/homes.csv'
df = pd.read_csv(url)
df

,Sell,"""List""","""Living""","""Rooms""","""Beds""","""Baths""","""Age""","""Acres""","""Taxes"""
0,142,160,28,10,5,3,60,0.28,3167
1,175,180,18,8,4,1,12,0.43,4033
2,129,132,13,6,3,1,41,0.33,1471
3,138,140,17,7,3,1,22,0.46,3204
4,232,240,25,8,4,3,5,2.05,3613
5,135,140,18,7,4,3,9,0.57,3028
6,150,160,20,8,4,3,18,4.00,3131
7,207,225,22,8,4,2,16,2.22,5158
8,271,285,30,10,5,2,30,0.53,5702
9,89,90,10,5,3,1,43,0.30,2054
10,153,157,22,8,3,3,18,0.38,4127
11,87,90,16,7,3,1,50,0.65,1445
12,234,238,25,8,4,2,2,1.61,2087
13,106,116,20,8,4,1,13,0.22,2818
14,175,180,22,8,4,2,15,2.06,3917
15,165,170,17,8,4,2,33,0.46,2220
16,166,170,23,9,4,2,37,0.27,3498
17,136,140,19,7,3,1,22,0.63,3607
18,148,160,17,7,3,2,13,0.36,3648
19,151,153,19,8,4,2,24,0.34,3561
20,180,190,24,9,4,2,10,1.55,4681
21,293,305,26,8,4,3,6,0.46,7088
22,167,170,20,9,4,2,46,0.46,3482
23,190,193,22,9,5,2,37,0.48,3920
24,184,190,21,9,5,2,27,1.30,4162
25,157,165,20,8,4,2,7,0.30,3785
26,110,115,16,8,4,1,26,0.29,3103
27,135,145,18,7,4,1,35,0.43,3363
28,567,625,64,11,4,4,4,0.85,12192
29,180,185,20,8,4,2,11,1.00,3831
30,183,188,17,7,3,2,16,3.00,3564
31,185,193,20,9,3,2,56,6.49,3765
32,152,155,17,8,4,1,33,0.70,3361
33,148,153,13,6,3,2,22,0.39,3950
34,152,159,15,7,3,1,25,0.59,3055
35,146,150,16,7,3,1,31,0.36,2950
36,170,190,24,10,3,2,33,0.57,3346
37,127,130,20,8,4,1,65,0.40,3334
38,265,270,36,10,6,3,33,1.20,5853
39,157,163,18,8,4,2,12,1.13,3982
40,128,135,17,9,4,1,25,0.52,3374
41,110,120,15,8,4,2,11,0.59,3119
42,123,130,18,8,4,2,43,0.39,3268
43,212,230,39,12,5,3,202,4.29,3648
44,145,145,18,8,4,2,44,0.22,2783
45,129,135,10,6,3,1,15,1.00,2438
46,143,145,21,7,4,2,10,1.20,3529
47,247,252,29,9,4,2,4,1.25,4626
48,111,120,15,8,3,1,97,1.11,3205
49,133,145,26,7,3,1,42,0.36,3059

Først må vi rydde opp i kolonnenavnene, som er litt rotete.

In [ ]:
display(df.columns)
df.columns= [x.strip().replace('"','') for x in df.columns]
display(df.columns)

Index(['Sell', ' "List"', ' "Living"', ' "Rooms"', ' "Beds"', ' "Baths"',
       ' "Age"', ' "Acres"', ' "Taxes"'],
      dtype='object')

Index(['Sell', 'List', 'Living', 'Rooms', 'Beds', 'Baths', 'Age', 'Acres',
       'Taxes'],
      dtype='object')

For å finne de tre dyreste hjemmene, kan vi bruke *df.sort_values* og *df.head()*

In [ ]:
df.sort_values('Sell',ascending=False).head(3)

    Sell  List  Living  Rooms  Beds  Baths  Age  Acres  Taxes
28   567   625      64     11     4      4    4   0.85  12192
21   293   305      26      8     4      3    6   0.46   7088
8    271   285      30     10     5      2   30   0.53   5702

Vi kan også sortere etter flere kolonner ved hjelp av lister:    
'Rooms' i synkende rekkefølge og 'Age' i stigende rekkefølge

In [ ]:
df.sort_values(['Rooms','Age'],ascending=[False,True])

    Sell  List  Living  Rooms  Beds  Baths  Age  Acres  Taxes
43   212   230      39     12     5      3  202   4.29   3648
28   567   625      64     11     4      4    4   0.85  12192
8    271   285      30     10     5      2   30   0.53   5702
36   170   190      24     10     3      2   33   0.57   3346
38   265   270      36     10     6      3   33   1.20   5853
0    142   160      28     10     5      3   60   0.28   3167
47   247   252      29      9     4      2    4   1.25   4626
20   180   190      24      9     4      2   10   1.55   4681
40   128   135      17      9     4      1   25   0.52   3374
24   184   190      21      9     5      2   27   1.30   4162
16   166   170      23      9     4      2   37   0.27   3498
23   190   193      22      9     5      2   37   0.48   3920
22   167   170      20      9     4      2   46   0.46   3482
31   185   193      20      9     3      2   56   6.49   3765
12   234   238      25      8     4      2    2   1.61   2087
4    232   240      25      8     4      3    5   2.05   3613
21   293   305      26      8     4      3    6   0.46   7088
25   157   165      20      8     4      2    7   0.30   3785
29   180   185      20      8     4      2   11   1.00   3831
41   110   120      15      8     4      2   11   0.59   3119
1    175   180      18      8     4      1   12   0.43   4033
39   157   163      18      8     4      2   12   1.13   3982
13   106   116      20      8     4      1   13   0.22   2818
14   175   180      22      8     4      2   15   2.06   3917
7    207   225      22      8     4      2   16   2.22   5158
6    150   160      20      8     4      3   18   4.00   3131
10   153   157      22      8     3      3   18   0.38   4127
19   151   153      19      8     4      2   24   0.34   3561
26   110   115      16      8     4      1   26   0.29   3103
15   165   170      17      8     4      2   33   0.46   2220
32   152   155      17      8     4      1   33   0.70   3361
42   123   130      18      8     4      2   43   0.39   3268
44   145   145      18      8     4      2   44   0.22   2783
37   127   130      20      8     4      1   65   0.40   3334
48   111   120      15      8     3      1   97   1.11   3205
5    135   140      18      7     4      3    9   0.57   3028
46   143   145      21      7     4      2   10   1.20   3529
18   148   160      17      7     3      2   13   0.36   3648
30   183   188      17      7     3      2   16   3.00   3564
3    138   140      17      7     3      1   22   0.46   3204
17   136   140      19      7     3      1   22   0.63   3607
34   152   159      15      7     3      1   25   0.59   3055
35   146   150      16      7     3      1   31   0.36   2950
27   135   145      18      7     4      1   35   0.43   3363
49   133   145      26      7     3      1   42   0.36   3059
11    87    90      16      7     3      1   50   0.65   1445
45   129   135      10      6     3      1   15   1.00   2438
33   148   153      13      6     3      2   22   0.39   3950
2    129   132      13      6     3      1   41   0.33   1471
9     89    90      10      5     3      1   43   0.30   2054

For å finne gjennomsnittsprisen for hjemmene gruppert etter antall rom kan vi bruke *df.groupby()* og *df.mean()*. Hvis noen av kolonnene inneholder noe annet enn numeriske verdier, må vi bruke numeric_only = True

In [ ]:
df.groupby(df['Rooms']).mean(numeric_only=True)

,Sell,List,Living,Beds,Baths,Age,Acres,Taxes
Rooms,,,,,,,,
5,89.000000,90.000000,10.000000,3.000000,1.000000,43.000000,0.300000,2054.000000
6,135.333333,140.000000,12.000000,3.000000,1.333333,26.000000,0.573333,2619.666667
7,139.636364,145.636364,18.181818,3.272727,1.454545,25.000000,0.782727,3132.000000
8,162.523810,169.142857,19.666667,3.904762,1.904762,24.333333,0.969524,3596.380952
9,180.875000,186.625000,22.000000,4.125000,1.875000,30.250000,1.540000,3938.500000
10,212.000000,226.250000,29.500000,4.750000,2.500000,39.000000,0.645000,4517.000000
11,567.000000,625.000000,64.000000,4.000000,4.000000,4.000000,0.850000,12192.000000
12,212.000000,230.000000,39.000000,5.000000,3.000000,202.000000,4.290000,3648.000000

Det finnes flere ulike matematiske operasjoner vi kan bruke, mean, min, max, osv. Her bruker vi *min* til å vise den billigste salgsprisen gruppert etter antall rom.

In [ ]:
df[['Rooms','Sell']].groupby(df['Rooms']).min()

       Rooms  Sell
Rooms
5          5    89
6          6   129
7          7    87
8          8   106
9          9   128
10        10   142
11        11   567
12        12   212

Smidig IT-2 © TIP AS, 2024